import '../features/restaurants/data/models/restaurant.dart';

final List<Restaurant> dummyRestaurants = [
  const Restaurant(
    id: '1',
    name: 'Damascus Gate',
    address: '10 Camden Street Lower, Dublin 2',
    rating: 4.7,
    cuisine: ['Syrian', 'Middle Eastern'],
    isHalalCertified: true,
    halalCertification: 'HCI',
    phone: '+353 1 555 1234',
  ),
  const Restaurant(
    id: '2',
    name: 'Zaytoon',
    address: '14 Parliament Street, Temple Bar, Dublin 2',
    rating: 4.5,
    cuisine: ['Persian', 'Kebab'],
    isHalalCertified: true,
    halalCertification: 'IFI',
    phone: '+353 1 555 5678',
  ),
  const Restaurant(
    id: '3',
    name: 'Umi Falafel',
    address: '13 Dame Street, Dublin 2',
    rating: 4.6,
    cuisine: ['Falafel', 'Lebanese', 'Vegetarian'],
    isHalalCertified: true,
    halalCertification: 'HCI',
    phone: '+353 1 555 9012',
  ),
  const Restaurant(
    id: '4',
    name: 'Kinara Kitchen',
    address: '17 Ranelagh Road, Dublin 6',
    rating: 4.4,
    cuisine: ['Pakistani', 'Indian'],
    isHalalCertified: true,
    halalCertification: 'HCI',
    phone: '+353 1 555 3456',
  ),
  const Restaurant(
    id: '5',
    name: 'Shouk',
    address: '40 Drumcondra Road Lower, Drumcondra, Dublin 9',
    rating: 4.8,
    cuisine: ['Middle Eastern', 'Vegetarian'],
    isHalalCertified: true,
    halalCertification: 'HCI',
    phone: '+353 1 555 7890',
  ),
];
